// 按需引入，这里是全部引入，如果有不需要引入的组件自行删除即可，可减少打包体积
import {
  ElAlert,
  ElAside,
  ElAutocomplete,
  ElAvatar,
  ElBacktop,
  ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  ElButtonGroup,
  ElCalendar,
  ElCard,
  ElCarousel,
  ElCarouselItem,
  ElCascader,
  ElCascaderPanel,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElCol,
  ElCollapse,
  ElCollapseItem,
  ElCollapseTransition,
  ElColorPicker,
  ElContainer,
  ElDatePicker,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElFooter,
  ElForm,
  ElFormItem,
  ElHeader,
  ElIcon,
  ElImage,
  ElInput,
  ElInputNumber,
  ElLink,
  ElMain,
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElOption,
  ElOptionGroup,
  ElPageHeader,
  ElPagination,
  ElPopconfirm,
  ElPopover,
  ElPopper,
  ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElRate,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElSlider,
  ElStep,
  ElSteps,
  ElSwitch,
  ElTabPane,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElCheckTag,
  ElTag,
  ElTimePicker,
  ElTimeSelect,
  ElTimeline,
  ElTimelineItem,
  ElTooltip,
  ElTransfer,
  ElTree,
  ElUpload,
  ElInfiniteScroll,
  ElLoading,
  ElMessage,
  ElMessageBox,
  ElNotification
} from 'element-plus'

export default app => {
  app.use(ElAlert)
  app.use(ElAside)
  app.use(ElAutocomplete)
  app.use(ElAvatar)
  app.use(ElBacktop)
  app.use(ElBadge)
  app.use(ElBreadcrumb)
  app.use(ElBreadcrumbItem)
  app.use(ElButton)
  app.use(ElButtonGroup)
  app.use(ElCalendar)
  app.use(ElCard)
  app.use(ElCarousel)
  app.use(ElCarouselItem)
  app.use(ElCascader)
  app.use(ElCascaderPanel)
  app.use(ElCheckbox)
  app.use(ElCheckboxButton)
  app.use(ElCheckboxGroup)
  app.use(ElCol)
  app.use(ElCollapse)
  app.use(ElCollapseItem)
  app.use(ElCollapseTransition)
  app.use(ElColorPicker)
  app.use(ElContainer)
  app.use(ElDatePicker)
  app.use(ElDialog)
  app.use(ElDivider)
  app.use(ElDrawer)
  app.use(ElDropdown)
  app.use(ElDropdownItem)
  app.use(ElDropdownMenu)
  app.use(ElFooter)
  app.use(ElForm)
  app.use(ElFormItem)
  app.use(ElHeader)
  app.use(ElIcon)
  app.use(ElImage)
  app.use(ElInput)
  app.use(ElInputNumber)
  app.use(ElLink)
  app.use(ElMain)
  app.use(ElMenu)
  app.use(ElMenuItem)
  app.use(ElMenuItemGroup)
  app.use(ElOption)
  app.use(ElOptionGroup)
  app.use(ElPageHeader)
  app.use(ElPagination)
  app.use(ElPopconfirm)
  app.use(ElPopover)
  app.use(ElPopper)
  app.use(ElProgress)
  app.use(ElRadio)
  app.use(ElRadioButton)
  app.use(ElRadioGroup)
  app.use(ElRate)
  app.use(ElRow)
  app.use(ElScrollbar)
  app.use(ElSelect)
  app.use(ElSlider)
  app.use(ElStep)
  app.use(ElSteps)
  app.use(ElSwitch)
  app.use(ElTabPane)
  app.use(ElTable)
  app.use(ElTableColumn)
  app.use(ElTabs)
  app.use(ElCheckTag)
  app.use(ElTag)
  app.use(ElTimePicker)
  app.use(ElTimeSelect)
  app.use(ElTimeline)
  app.use(ElTimelineItem)
  app.use(ElTooltip)
  app.use(ElTransfer)
  app.use(ElTree)
  app.use(ElUpload)
  app.use(ElInfiniteScroll)
  app.use(ElLoading)
  app.use(ElMessage)
  app.use(ElMessageBox)
  app.use(ElNotification)
}
